"use client";
import {create} from 'zustand';
import type { Product } from '@/lib/types';
// import { initialSeedProducts } from '@/data/products'; // Removido para não carregar dados fixos
import { v4 as uuidv4 } from 'uuid';


interface ProductAdminState {
  products: Product[];
  addProduct: (productData: Omit<Product, 'id'>) => void;
  updateProduct: (productId: string, productData: Partial<Omit<Product, 'id'>>) => void;
  deleteProduct: (productId: string) => void;
  getProductById: (productId: string) => Product | undefined;
  setProducts: (products: Product[]) => void; 
}

// Helper to ensure all products have new fields, even if loaded from old data structure
// Also ensures ID exists.
const ensureProductFields = (product: any, existingId?: string): Product => ({
  id: existingId || product.id || uuidv4(), // Use existing ID if updating, else product.id, else generate
  name: product.name || '',
  description: product.description || '',
  price: typeof product.price === 'number' ? product.price : 0,
  image: product.image || `https://picsum.photos/seed/${uuidv4()}/400/300`, // default placeholder with random seed
  category: product.category,
  dataAiHint: product.dataAiHint,
  color: product.color,
  size: product.size,
  model: product.model,
});

// const hydratedInitialProducts = initialSeedProducts.map(p => ensureProductFields(p)); // Removido

export const useProductAdminStore = create<ProductAdminState>((set, get) => ({
  products: [], // Inicia com a lista de produtos vazia
  addProduct: (productData) => {
    // TODO: Em uma aplicação real, esta função faria uma chamada a uma API para salvar o produto no banco de dados.
    const newProduct: Product = ensureProductFields(productData); // ID will be generated by ensureProductFields
    set((state) => ({ products: [...state.products, newProduct] }));
  },
  updateProduct: (productId, productData) => {
    // TODO: Em uma aplicação real, esta função faria uma chamada a uma API para atualizar o produto no banco de dados.
    set((state) => ({
      products: state.products.map((p) =>
        p.id === productId ? ensureProductFields({ ...p, ...productData }, productId) : p
      ),
    }));
  },
  deleteProduct: (productId) => {
    // TODO: Em uma aplicação real, esta função faria uma chamada a uma API para deletar o produto no banco de dados.
    set((state) => ({
      products: state.products.filter((p) => p.id !== productId),
    }));
  },
  getProductById: (productId) => {
    // TODO: Em uma aplicação real, esta função poderia buscar o produto de uma API/banco de dados se não estiver no estado local.
    return get().products.find((p) => p.id === productId);
  },
  setProducts: (newProducts) => {
    // Usado para popular o store, por exemplo, após buscar produtos de uma API.
    set({ products: newProducts.map(p => ensureProductFields(p)) });
  }
}));

// Note: Product changes in this store are in-memory and will be lost on browser refresh/server restart.
// For persistence, a backend/database solution (e.g., SQLite, PostgreSQL, Firebase Firestore) is required.
// O arquivo `banco.sql` seria usado para inicializar o esquema e dados desse banco de dados.

