"use client";
import {create} from 'zustand';
import type { Product } from '@/lib/types';
import { products as initialProducts } from '@/data/products'; 
// Note: Using a real UUID library is better for production if IDs need to be truly unique.
// For this example, a simple counter or Math.random based ID might suffice if not persisting.
// Let's use a simple timestamp-based ID generator for now to avoid new dependencies unless specified.
const generateId = () => String(Date.now() + Math.random().toString(36).substring(2, 9));


interface ProductAdminState {
  products: Product[];
  addProduct: (productData: Omit<Product, 'id'>) => void;
  updateProduct: (productId: string, productData: Partial<Omit<Product, 'id'>>) => void;
  deleteProduct: (productId: string) => void;
  getProductById: (productId: string) => Product | undefined;
  setProducts: (products: Product[]) => void; 
}

// Helper to ensure all products have new fields, even if loaded from old data structure
// Also ensures ID exists.
const ensureProductFields = (product: any, existingId?: string): Product => ({
  id: existingId || product.id || generateId(), // Use existing ID if updating, else product.id, else generate
  name: product.name || '',
  description: product.description || '',
  price: typeof product.price === 'number' ? product.price : 0,
  image: product.image || `https://picsum.photos/seed/${generateId()}/400/300`, // default placeholder with random seed
  category: product.category,
  dataAiHint: product.dataAiHint,
  color: product.color,
  size: product.size,
  model: product.model,
});

const hydratedInitialProducts = initialProducts.map(p => ensureProductFields(p));

export const useProductAdminStore = create<ProductAdminState>((set, get) => ({
  products: hydratedInitialProducts,
  addProduct: (productData) => {
    const newProduct: Product = ensureProductFields(productData); // ID will be generated by ensureProductFields
    set((state) => ({ products: [...state.products, newProduct] }));
  },
  updateProduct: (productId, productData) => {
    set((state) => ({
      products: state.products.map((p) =>
        p.id === productId ? ensureProductFields({ ...p, ...productData }, productId) : p
      ),
    }));
  },
  deleteProduct: (productId) => {
    set((state) => ({
      products: state.products.filter((p) => p.id !== productId),
    }));
  },
  getProductById: (productId) => {
    return get().products.find((p) => p.id === productId);
  },
  setProducts: (newProducts) => {
    set({ products: newProducts.map(p => ensureProductFields(p)) });
  }
}));

// Note: Product changes in this store are in-memory and will be lost on browser refresh/server restart.
// For persistence, a backend/database solution is required.
